@host = http://localhost:5000/vpo/v1

###
POST {{host}}/users/register
Content-Type: application/json

{
    "username":"mike",
    "password":"12345"
}

####
POST {{host}}/login

{
    "username":"mike",
    "password":"12345"
}
